### ISSUE TITLE
Allgemeiner Right Anti Join is not working correctly

### ISSUE THREAD

**Issue by FelsyWaschbaer** [harald-lang/ira#19]
The result set seems to be always empty. Try for example: pruefen rigth anti join Studenten on pruefen.MatrNr = Studenten.MatrNr

**Comment by mathiasquintero** [comment]
It only seems to happen with the conditional right anti join... I will look into it

**Comment by mathiasquintero** [comment]
@FelsyWaschbaer 
The fix is done, but it isn't live yet. We like to be careful about the changes we do.
There is a version we have on the side with all the changes we still want to test. 
Mostly for alpha Testing.

But if you really want to use the conditional right anti join: http://mathiasquintero.github.io/ira/
**Warning: This is an Alpha version and hasn't been sufficiently tested.
